### PR TITLE
Fix window is not defined in next.js + bump deps

### LINKED ISSUE #55: undefined window and Synchronous isLoggedIn
For some reason, the new swappable storage interface has caused isLoggedIn to not excecute properly on initial page load. For example, in my app im using it to set the ui state for logged in vs not logged in users and now it returns false on page load (onmount useeffect) and true only later, rendering the wrong ui state.

Furthermore, when trying to build the app, getBrowserLocalStorage is causing a ReferenceError: window is not defined t be thrown

### PR DESCRIPTION
**Pull request by moshfrid**
Fix this up for code running in server or hybrid environments. Closes #55.
Also drops support for 0.x.x axios versions in favor of 1.x.x

### CODE REVIEW

File: src/authTokenInterceptor.ts [hunk 1]
```diff
@@ -179,7 +178,9 @@ export const authTokenInterceptor = ({
     ms(typeof tokenExpireFudge === 'string' ? tokenExpireFudge : `${tokenExpireFudge}s`) / 1000
   applyStorage(getStorage())
 
-  return async (requestConfig: AxiosRequestConfig): Promise<AxiosRequestConfig> => {
+  // eslint-disable-next-line  @typescript-eslint/no-explicit-any -- Waiting for a fix in axios types
+  return async (requestConfig: any): Promise<any> => {
```
Comment (revmischa) [inline src/authTokenInterceptor.ts:182]: does it have to be `any`?

Comment (moshfrid) [reply src/authTokenInterceptor.ts:182]: As of now I wasn't able to resolve the new 'InternalAxios' types to the old ones
